#!/usr/bin/env bash

CONFIG_DIR="$HOME/.config/qemu"

function help() {
    message=(
        "USAGE:"
        "   qemu <SUBCOMMAND>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        ""
        "SUBCOMMANDS:"
        "   backup      Backup an existing virtual machine"
        "   clone       Clone an existing virtual machine"
        "   disk        Create a new disk"
        "   help        Print this message or the help of the given subcommand(s)"
        "   install     Create and install a new virtual machine"
        "   list        Print the names of all installed virtual machines"
        "   remove      Uninstall a virtual machine"
        "   restore     Restore a virtual machine from an existing backup"
        "   shutdown    Terminate a running virtual machine"
        "   start       Start up a virtual machine"
    )

    if [[ $# -gt 1 ]]; then
        subcommand=$2
        case $subcommand in
        "install")
            help_install $@
            exit 0
            ;;
        "start")
            help_start $@
            exit 0
            ;;
        "shutdown")
            help_shutdown $@
            exit 0
            ;;
        "clone")
            help_clone $@
            exit 0
            ;;
        "list")
            help_list $@
            exit 0
            ;;
        "remove")
            help_remove $@
            exit 0
            ;;
        "backup")
            help_backup $@
            exit 0
            ;;
        "restore")
            help_restore $@
            exit 0
            ;;
        "disk")
            help_disk $@
            exit 0
            ;;
        *)
            echo "qemu: unknown subcommand: $subcommand"
            printf "%s\n" "${message[@]}"
            exit 1
            ;;
        esac
    fi

    printf "%s\n" "${message[@]}"
}

function help_install() {
    message=(
        "USAGE:"
        "   qemu install [OPTIONS] -n <NAME> -i <ISO>"
        ""
        "OPTIONS:"
        "   -c  Cores for virtual machine [default: 2]"
        "   -h  Print help information"
        "   -i  ISO to install on virtual machine"
        "   -m  Memory (gigabytes) for virtual machine [default: 8]"
        "   -n  Name of virtual machine"
        "   -s  Disk size (gigabytes) for virtual machine in [default: 256]"
    )
    printf "%s\n" "${message[@]}"
}

function help_start() {
    message=(
        "USAGE:"
        "   qemu start [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -c  Cores for virtual machine [default: 2]"
        "   -d  Name of optional disk to attach"
        "   -h  Print help information"
        "   -m  Memory (gigabytes) for virtual machine [default: 8]"
        "   -n  Name of virtual machine"
        "   -p  Port to forward to [default: 8080]"
    )
    printf "%s\n" "${message[@]}"
}

function help_shutdown() {
    message=(
        "USAGE:"
        "   qemu shutdown [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -n  Name of virtual machine"
    )
    printf "%s\n" "${message[@]}"
}

function help_clone() {
    message=(
        "USAGE:"
        "   qemu clone [OPTIONS] -s <NAME> -d <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -s  Name of existing virtual machine"
        "   -d  Name of cloned virtual machine"
    )
    printf "%s\n" "${message[@]}"
}

function help_list() {
    message=(
        "USAGE:"
        "   qemu list [OPTIONS]"
        ""
        "OPTIONS:"
        "   -h  Print help information"
    )
    printf "%s\n" "${message[@]}"
}

function help_remove() {
    message=(
        "USAGE:"
        "   qemu list [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -n  Name of virtual machine to remove"
    )
    printf "%s\n" "${message[@]}"
}

function help_backup() {
    message=(
        "USAGE:"
        "   qemu backup [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -n  Name of virtual machine to backup"
    )
    printf "%s\n" "${message[@]}"
}

function help_restore() {
    message=(
        "USAGE:"
        "   qemu restore [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -n  Name of backed up virtual machine to restore"
    )
    printf "%s\n" "${message[@]}"
}

function help_disk() {
    message=(
        "USAGE:"
        "   qemu disk [OPTIONS] -n <NAME>"
        ""
        "OPTIONS:"
        "   -h  Print help information"
        "   -n  Name of disk to create"
        "   -s  Size of disk [default: 128G]"
    )
    printf "%s\n" "${message[@]}"
}

function install() {
    name=""
    iso=""
    cores=4
    memory=8
    size=256
    uefi="$(brew --prefix qemu)/share/qemu/edk2-aarch64-code.fd"

    while getopts "n:i:c:m:s:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/machines/$OPTARG.qcow2
            ;;
        i)
            iso=$OPTARG
            ;;
        c)
            cores=$OPTARG
            ;;
        m)
            memory=$OPTARG
            ;;
        s)
            size=$OPTARG
            ;;
        h)
            help_install $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_install $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to create"
        exit 1
    fi

    if [[ -z $iso ]]; then
        echo "qemu: missing path to ISO to install"
        exit 1
    fi

    qemu-img create -f qcow2 $name ${size}G

    qemu-system-aarch64 \
        -M virt,highmem=on \
        -accel hvf \
        -cpu host \
        -smp $cores \
        -m ${memory}G \
        -bios $uefi \
        -drive file=$name,if=none,cache=writethrough,id=hd0 \
        -device virtio-gpu-pci \
        -device virtio-blk-device,drive=hd0 \
        -nographic \
        -cdrom $iso
}

function start() {
    name=""
    cores=4
    memory=8
    port=8080
    disk=""
    uefi="$(brew --prefix qemu)/share/qemu/edk2-aarch64-code.fd"

    while getopts "n:c:m:p:d:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/machines/$OPTARG.qcow2
            ;;
        c)
            cores=$OPTARG
            ;;
        m)
            memory=$OPTARG
            ;;
        p)
            port=$OPTARG
            ;;
        d)
            disk=$CONFIG_DIR/disks/$OPTARG.qcow2
            ;;
        h)
            help_start $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_start $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to start"
        exit 1
    fi

    if [[ -z $disk ]]; then
        qemu-system-aarch64 \
            -M virt,highmem=on \
            -accel hvf \
            -cpu host \
            -smp $cores \
            -m ${memory}G \
            -bios $uefi \
            -drive file=$name,if=none,cache=writethrough,id=hd0 \
            -device virtio-gpu-pci \
            -device virtio-blk-device,drive=hd0 \
            -nographic \
            -net user,hostfwd=tcp::$port-:22 \
            -net nic
            # -net user,hostfwd=tcp::$port-:22,hostfwd=tcp::9797-:80,hostfwd=tcp::9898-:9000 \
    else
        qemu-system-aarch64 \
            -M virt,highmem=on \
            -accel hvf \
            -cpu host \
            -smp $cores \
            -m ${memory}G \
            -bios $uefi \
            -drive file=$name,if=none,cache=writethrough \
            -device virtio-gpu-pci \
            -device virtio-blk-device,drive=hd0 \
            -drive file=$disk,format=qcow2,media=disk \
            -nographic \
            -net user,hostfwd=tcp::$port-:22 \
            -net nic
            # -net user,hostfwd=tcp::$port-:22,hostfwd=tcp::9797-:80,hostfwd=tcp::9898-:9000 \
    fi
}

function shutdown() {
    name=""

    while getopts "n:h" opt; do
        case $opt in
        n)
            name=$OPTARG
            ;;
        h)
            help_shutdown $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_shutdown $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to shutdown"
        exit 1
    fi

    kill $(ps aux | egrep ".*qemu-system-aarch64.*$name.*" | egrep -v egrep | awk '{ print $2 }')
}

function clone() {
    src=""
    dst=""
    src_name=""
    dst_name=""

    while getopts "s:d:h" opt; do
        case $opt in
        s)
            src_name=$OPTARG
            src=$CONFIG_DIR/machines/$OPTARG.qcow2
            ;;
        d)
            dst_name=$OPTARG
            dst=$CONFIG_DIR/machines/$OPTARG.qcow2
            ;;
        h)
            help_clone $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_clone $@
            exit 1
            ;;
        esac
    done

    if [[ -z $src ]]; then
        echo "qemu: missing name of existing virtual machine"
        exit 1
    fi

    if [[ -z $dst ]]; then
        echo "qemu: missing name of cloned virtual machine"
        exit 1
    fi

    echo -n "qemu: cloning $src_name to $dst_name... "
    cp $src $dst
    echo "done."
}

function list() {
    while getopts "h" opt; do
        case $opt in
        h)
            help_list $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_list $@
            exit 1
            ;;
        esac
    done

    for vm in $CONFIG_DIR/machines/*.qcow2; do
        name=$(basename $vm)
        echo ${name%.*}
    done
}

function remove() {
    name=""

    while getopts "n:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/machines/$OPTARG.qcow2
            ;;
        h)
            help_remove $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_remove $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to remove"
        exit 1
    fi

    if [[ ! -f $name ]]; then
        echo "qemu: virtual machine does not exist"
        exit 1
    fi

    echo -n "qemu: removing virtual machine... "
    rm -f $name
    echo "done."
}

function backup() {
    name=""
    backup_name=""

    while getopts "n:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/machines/$OPTARG.qcow2
            backup_name=$CONFIG_DIR/machines/$OPTARG.bak.qcow2
            ;;
        h)
            help_backup $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_backup $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to backup"
        exit 1
    fi

    echo -n "qemu: backing up virtual machine... "
    cp $name $backup_name
    echo "done."
}

function restore() {
    name=""
    backup_name=""

    while getopts "n:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/machines/$OPTARG.qcow2
            backup_name=$CONFIG_DIR/machines/$OPTARG.bak.qcow2
            ;;
        h)
            help_restore $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_restore $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of virtual machine to backup"
        exit 1
    fi

    echo -n "qemu: restoring virtual machine... "
    cp $backup_name $name
    echo "done."
}

function disk() {
    name=""
    size=128

    while getopts "n:s:h" opt; do
        case $opt in
        n)
            name=$CONFIG_DIR/disks/$OPTARG.qcow2
            ;;
        s)
            size=$OPTARG
            ;;
        h)
            help_disk $@
            exit 0
            ;;
        *)
            echo "qemu: unknown option: $opt"
            help_disk $@
            exit 1
            ;;
        esac
    done

    if [[ -z $name ]]; then
        echo "qemu: missing name of disk to create"
        exit 1
    fi

    echo -n "qemu: creating disk... "
    qemu-img create -f qcow2 $name ${size}G &> /dev/null
    echo "done."
}

if [[ ! -d $CONFIG_DIR ]]; then
    echo -n "qemu: missing config directory, creating... "
    mkdir -p $CONFIG_DIR
    echo "done."
fi

if [[ ! -d "$CONFIG_DIR/machines" ]]; then
    echo -n "qemu: missing virtual machine directory, creating... "
    mkdir -p "$CONFIG_DIR/machines"
    echo "done."
fi

if [[ ! -d "$CONFIG_DIR/disks" ]]; then
    echo -n "qemu: missing disk directory, creating... "
    mkdir -p "$CONFIG_DIR/disks"
    echo "done."
fi

subcommand=$1
case $subcommand in
"" | "-h" | "help")
    help $@
    ;;
"install")
    shift
    install $@
    ;;
"start")
    shift
    start $@
    ;;
"shutdown")
    shift
    shutdown $@
    ;;
"clone")
    shift
    clone $@
    ;;
"list")
    shift
    list $@
    ;;
"remove")
    shift
    remove $@
    ;;
"backup")
    shift
    backup $@
    ;;
"restore")
    shift
    restore $@
    ;;
"disk")
    shift
    disk $@
    ;;
*)
    echo "qemu: unknown subcommand: $subcommand"
    help
    exit 1
    ;;
esac
